// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: average_service.proto

package second_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AvgService_SendNumber_FullMethodName = "/second_proto.AvgService/SendNumber"
)

// AvgServiceClient is the client API for AvgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AvgServiceClient interface {
	SendNumber(ctx context.Context, opts ...grpc.CallOption) (AvgService_SendNumberClient, error)
}

type avgServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAvgServiceClient(cc grpc.ClientConnInterface) AvgServiceClient {
	return &avgServiceClient{cc}
}

func (c *avgServiceClient) SendNumber(ctx context.Context, opts ...grpc.CallOption) (AvgService_SendNumberClient, error) {
	stream, err := c.cc.NewStream(ctx, &AvgService_ServiceDesc.Streams[0], AvgService_SendNumber_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &avgServiceSendNumberClient{stream}
	return x, nil
}

type AvgService_SendNumberClient interface {
	Send(*Request) error
	Recv() (*AvgResponse, error)
	grpc.ClientStream
}

type avgServiceSendNumberClient struct {
	grpc.ClientStream
}

func (x *avgServiceSendNumberClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *avgServiceSendNumberClient) Recv() (*AvgResponse, error) {
	m := new(AvgResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AvgServiceServer is the server API for AvgService service.
// All implementations must embed UnimplementedAvgServiceServer
// for forward compatibility
type AvgServiceServer interface {
	SendNumber(AvgService_SendNumberServer) error
	mustEmbedUnimplementedAvgServiceServer()
}

// UnimplementedAvgServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAvgServiceServer struct {
}

func (UnimplementedAvgServiceServer) SendNumber(AvgService_SendNumberServer) error {
	return status.Errorf(codes.Unimplemented, "method SendNumber not implemented")
}
func (UnimplementedAvgServiceServer) mustEmbedUnimplementedAvgServiceServer() {}

// UnsafeAvgServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AvgServiceServer will
// result in compilation errors.
type UnsafeAvgServiceServer interface {
	mustEmbedUnimplementedAvgServiceServer()
}

func RegisterAvgServiceServer(s grpc.ServiceRegistrar, srv AvgServiceServer) {
	s.RegisterService(&AvgService_ServiceDesc, srv)
}

func _AvgService_SendNumber_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AvgServiceServer).SendNumber(&avgServiceSendNumberServer{stream})
}

type AvgService_SendNumberServer interface {
	Send(*AvgResponse) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type avgServiceSendNumberServer struct {
	grpc.ServerStream
}

func (x *avgServiceSendNumberServer) Send(m *AvgResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *avgServiceSendNumberServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AvgService_ServiceDesc is the grpc.ServiceDesc for AvgService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AvgService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "second_proto.AvgService",
	HandlerType: (*AvgServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendNumber",
			Handler:       _AvgService_SendNumber_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "average_service.proto",
}
